# ~/bin/chromedriver
# Generated by Selenium IDE

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def wait_for_window(self, timeout = 2):
  time.sleep(round(timeout / 1000))
  wh_now = self.driver.window_handles
  wh_then = self.vars["window_handles"]
  if len(wh_now) > len(wh_then):
    return set(wh_now).difference(set(wh_then)).pop()

def test_zhihu():
  driver = webdriver.Chrome()
  #object of ChromeOptions class
  o = webdriver.ChromeOptions()
  #adding specific Chrome Profile Path
  o.add_arguments = {'user-data-dir':'/tmp/chrome'}
  #set chromedriver.exe path
  driver = webdriver.Chrome( options=o)
  vars = {}
  driver.get("https://www.zhihu.com/question/596228140")
  driver.set_window_size(920, 1056)
  driver.implicitly_wait(0.5)
  driver.find_element(By.CSS_SELECTOR, ".Modal-closeIcon").click()
  element = driver.find_element(By.CSS_SELECTOR, "body")
  actions = ActionChains(driver)
  actions.move_to_element_with_offset(element, 0, 0).perform()

  xpath = '//*[@id="QuestionAnswers-answers"]/div/div/div/div[2]/div'
  driver.execute_script(f'document.evaluate("{xpath}", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.remove();')

  element = driver.find_element(By.CSS_SELECTOR, "body")
  actions = ActionChains(driver)
  driver.find_element(By.CSS_SELECTOR, ".QuestionPage").click()
  driver.execute_script("window.scrollTo(0,812)")
  l = driver.find_element_by_css_selector("body")
  print("HTML code of element: " + l.get_attribute('QuestionAnswers-answers'))
  print(driver.title)
  #close browser
  driver.close()









test_zhihu()














